#!/bin/sh

if [ -z "$1" ] ; then
	echo "Usage:"
	echo "  $0 name [name:password]"
	exit 1
fi

name="$1"
destdir="/var/lib/zope/$name"

if [ -n "$2" ] ; then
	namepass="-u $2"
else
	namepass=""
fi

umask 006

install -d "/etc/zope/$name"
cp -a /etc/zope/skel/etc/* "/etc/zope/$name"

install -d "${destdir}"
cp -a /etc/zope/skel/{Extensions,Products,import,var} "$destdir"
chown root.zope "${destdir}/var"
chown zope.zope "${destdir}/var"/*
chmod 1771 "${destdir}/var" 

install -d "/var/log/zope/$name"
chown root.zope "${destdir}" "/var/log/zope/$name"
chmod 770 "/var/log/zope/$name"

echo "Set the initial user password with: zpasswd ${destdir}/inituser" >&2
